[tool.poetry]
name = "etl-spark"
version = "0.1.0"
description = ""
authors = ["breno jacubovski"]
readme = "README.md"

[tool.poetry.dependencies]
numpy = "^1.20.2"
pandas = "^2.0.0"
pyarrow = "^12.0.0"
# This is pinned to stay in sync with the version
# That gets downloaded in `.gitpod.Dockerfile`
pyspark = "3.5.1"
python = "~3.11"

[tool.poetry.dev-dependencies]
pylint = "^2.8.2"
pytest = "^6.2.4"
mypy = "^0.910"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
